version: '3'
networks:
  inception-networks:
    driver: bridge
    name: inception-yuva

volumes:
  mariadb_db:
    driver: local
    driver_opts:
      type: volume
      device: /home/pthink/data/mariadb
      o: bind

  wordpress_vol:
    driver: local
    driver_opts:
      type: volume
      device: /home/pthink/data/wp
      o: bind

services:
  wordpress:
    build: ./requirements/wordpress/
    image : wordpress:yuva
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html:rw
    networks:
      - inception-networks

  mariadb:
    build: ./requirements/mariadb/
    image : mariadb:yuva
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_db:/var/lib/mysql:rw
    networks:
      - inception-networks

  nginx:
    build: ./requirements/nginx/
    image: nginx:yuva
    container_name: nginx
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/html:rw
    networks:
      - inception-networks
